# Generated by Django 4.2.3 on 2023-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_donator_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
