# Generated by Django 4.2.3 on 2023-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepub', '0007_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
