# Generated by Django 4.2.3 on 2023-08-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codepub', '0011_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Chat',
        ),
    ]
