# Generated by Django 4.1.7 on 2023-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_user_profile_citizenid_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default_profile_img.png', upload_to='profile_images'),
        ),
    ]
