# Generated by Django 4.1.7 on 2023-07-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='Default-avatar.jpg', upload_to='profile_images'),
        ),
    ]
