# Generated by Django 4.2.3 on 2023-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='moderator',
            field=models.IntegerField(default=0),
        ),
    ]
