# Generated by Django 4.2.3 on 2023-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attendants',
            field=models.IntegerField(default=0),
        ),
    ]
