# Generated by Django 4.2.3 on 2023-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='moderator',
        ),
        migrations.AddField(
            model_name='profile',
            name='moderator',
            field=models.IntegerField(default=0),
        ),
    ]
